model: BaseModLSTM_v1
params:
    num_features: 6
    feature_window: 20
    num_kmers: 4096
    embedding_dim: 64
    padding_idx: 0
    dropout: 0.1
    input_nn_dims:
        - 64
        - 128
    rnn_type: 'LSTM'
    d_model: 512
    num_layer: 3
    num_classes: 2
