# \CONFIG\-------------------------------------------------------------------------
#
#  CONTENTS      : R94_450Bps_DNA_CG_5mC_v1
#
#  DESCRIPTION   : Nanopore Basecalling
#
#  RESTRICTIONS  : none
#
#  REQUIRES      : none
#
# ---------------------------------------------------------------------------------
# Copyright 2021 Pay Giesselmann, Max Planck Institute for Molecular Genetics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Written by Pay Giesselmann
# ---------------------------------------------------------------------------------
model: BaseModLSTM_v1
params:
  d_model: 512
  dropout: 0.1
  embedding_dim: 64
  feature_window: 20
  input_nn_dims:
  - 64
  - 128
  - 256
  num_classes: 2
  num_features: 6
  num_kmers: 4096
  num_layer: 4
  padding_idx: 0
  rnn_type: LSTM
pattern: CG
extension: 7
max_features: 40
